### ISSUE TITLE
xc.pl: Unknown reader: ini

### ISSUE THREAD

**Issue by probonopd** [ildar-shaimordanov/xml-yaml-json-ini#1]
On openSUSE LEAP 42.3, getting

```
linux@linux:~> perl xc.pl -f INI -t yaml ... 
xc.pl: Unknown reader: ini

linux@linux:~> perl xc.pl --from=ini -t yaml ... 
xc.pl: Unknown reader: ini
```

Had installed the dependencies with

```
sudo PERL_MM_USE_DEFAULT=1 perl -MCPAN -e 'install XML::Simple
sudo PERL_MM_USE_DEFAULT=1 perl -MCPAN -e 'install YAML::Tiny'
```

**Comment by ildar-shaimordanov** [comment]
@probonopd 
I am sorry. but converting from/to INI files is not implemented yet.

**Comment by probonopd** [comment]
OK. This was the reason for me to pick this project, maybe it would be worrthwhile to change the project description then ;-)

**Comment by ildar-shaimordanov** [comment]
@probonopd 
I would like to enable ini-files parsing by this script because it is quite simple and works fine for other formats. But I am a bit busy with main processes so it is question of time to implement the missing feature.

**Comment by ildar-shaimordanov** [comment]
@probonopd 
I would like to enable ini-files parsing by this script because it is quite simple and works fine for other formats. But I am a bit busy with main processes so it is question of time to implement the missing feature.

**Comment by ildar-shaimordanov** [comment]
hi @probonopd 

After 3 years i decided to revive this project and made some improvements. If you're still interested in it you can test it on your examples. Use the branch `ini`: https://github.com/ildar-shaimordanov/xml-yaml-json-ini/tree/ini

**Comment by ildar-shaimordanov** [comment]
INI -> others and others -> INI is available now in the master branch.
